### ISSUE TITLE
TypeError: Cannot read property 'counts' of null (`this.state` is null)

### ISSUE THREAD

**Issue by coreyward** [thomax/sanity-dashboard-widget-document-chart#1]
I installed this by running `sanity install dashboard-widget-document-chart` and adding `{ name: "document-chart" }` to my `widgets` array in `dashboardConfig.js`. I have a schema and content, but I receive this error that crashes the studio when I open the Dashboard:

> Stack trace:
  TypeError: Cannot read property 'counts' of null
    at DocumentChart.render (/static/js/app.bundle.js:153411:31)
    at finishClassComponent (/static/js/vendor.bundle.js:23197:31)
    at updateClassComponent (/static/js/vendor.bundle.js:23150:24)
    at beginWork$1 (/static/js/vendor.bundle.js:24907:16)

> Component stack:
    in DocumentChart (created by WidgetContainer)
    in div (created by WidgetContainer)
    in WidgetContainer (created by WidgetGroup)
    in div (created by WidgetGroup)
    in WidgetGroup (created by Dashboard)

Further, in the console I can see that the error is indeed coming from the `render` method on DocumentChart: 

> Uncaught TypeError: Cannot read property 'counts' of null
      at DocumentChart.render (index.js:97)

…which corresponds to this line in the source:

https://github.com/thomax/sanity-dashboard-widget-document-chart/blob/5d801985a738170cca724c99571c66543ebeb3c0/src/index.js#L62

**Comment by readeral** [comment]
I am also having this issue.

**Comment by thomax** [comment]
Thanks for the heads up @readeral and @coreyward. I'd totally forgotten about this half-finished piece of software. Please try out `v0.0.5` and let me know if there's a major fluke?

**Comment by thomax** [comment]
Closing this issue, until proven guilty :)
